### ISSUE TITLE
Feature Request: Support Readwise Annotation Codes

### ISSUE THREAD

**Issue by wenlzhang** [chrisgrieser/pdf-annotation-extractor-alfred#2]
Besides the current version of the Annotation Codes, is it also possible to support Annotation Codes with Readwise syntax? For instance, a few commonly used Annotation Codes/Tags in Readwise for me are as follows:

- If `.h1`, `.h2`, `.h3`, etc. are added to the comments corresponding to specific highlights, the highlighted text would be converted as Markdown headers of the corresponding levels.
- If `.c1`, `.c2`, `.c3`, etc. are added to the comments corresponding to specific highlights, the highlights and comments would be combined.
- For ordinary tags, one can use `.tag1`, `.tag2`, etc. in the comments.

A few other notes for adding tags in the Readwise syntax are as follows:

- Tags should be separated from each other with spaces, e.g. `.tag1 .tag2`.
- Tags should be separated from actual comments with new lines. For instance, the first line of the comments can be tags, and the second line can be actual comments.

A few related articles on this are as follows:

- [How to Combine Highlights On-the-Fly with Concatenation in Readwise](https://blog.readwise.io/combine-highlights-on-the-fly/)
- [How to Tag Your Highlights While You Read with Inline Tagging in Readwise](https://blog.readwise.io/tag-your-highlights-while-you-read/?cmdid=PP49A2RQBF27C3)

**Comment by chrisgrieser** [comment]
I'll have a look, but it might take a while; it might take a bit of time unfortunately, since I try to prioritize my other projects which have a few dozen times more users 😅 

But since some of those ideas look interesting really interesting, I'll definitely have a look 👀

**Comment by chrisgrieser** [comment]
Hi, sorry for the late response, got held up with a bunch of stuff. I looked into it, and as far as I can tell, the readwise annotation tags actually do less than my annotation tags. I couldn't find any feature that wasn't already covered; the only difference seems to be the syntax.

However, I am not sure about using the readwise syntax, since it appears to be more complicated than mine. And adding their syntax solely for consistency for the minority of users who use this workflow and also use readwise isn't really worth the time and effort in my view, sorry!
