### ISSUE TITLE
Feature Request: Support customizing note name when extracting annotations from PDF files that are not part of the BibTeX library

### ISSUE THREAD

**Issue by wenlzhang** [chrisgrieser/pdf-annotation-extractor-alfred#6]
### Feature Requested

It would be great if one can customize the note name when extracting annotations from PDF files that are not part of the BibTeX library, as one may already have existing daily notes. For instance, it would great if one can add a suffix or prefix, e.g., `2022-04-09_annotation.md`.

Taken from https://github.com/chrisgrieser/pdf-annotation-extractor-alfred/issues/5#issuecomment-1094104474.

### Checklist

- [X] The feature would be useful to more users than just me.
- [X] I have read the README and also checked that the `aconf` does not already offer an option for the feature I am requesting.

**Comment by chrisgrieser** [comment]
Okay, I made it so that the filename for a pdf without bibliography is `{date:yyyy-MM-dd HH-mm-ss}_annotations`, to avoid conflict with daily notes.

(not sure I wanna go down the road of coding more customization here, since this is actually an auxiliary feature of anyway, but if more people express interest, I'd reconsider.)

**Comment by wenlzhang** [comment]
Thanks for implementing this! This is enough for my initial request.
